<img src='images/Practicum_AI_Logo.white_outline.svg' width=250 alt='Practicum AI logo'> <img src='https://github.com/PracticumAI/practicumai.github.io/blob/main/images/icons/practicumai_beginner.png?raw=true' align='right' width=50>
***
# *Practicum AI:* Deep Learning - Perceptron

<img alt='A drawing of Amelia, our character for this exercise' src='images/amelia.png' align='right' width='200' padding=20>

> This exercise adapted from the [W3 Schools Perceptrons](https://www.w3schools.com/ai/ai_perceptrons.asp) article and from Baig et al. (2020) The Deep Learning Workshop from [Packt Publishers](https://www.packtpub.com/product/the-deep-learning-workshop/9781839219856) (Exercise 2.01, page 55).

 Amelia is back! We'll follow Amelia again in this example as she tries to dive into the inner workings of neurons and write her own code to implement a simple [perceptron](https://developers.google.com/machine-learning/glossary#perceptron) to decide if she should go to a concert or not. As a note, this exercise lies somewhere between coding everything from scratch and relying on the pre-coded APIs (Application Programming Interfaces) that underlie the power of TensorFlow, Keras, and Pytorch. You will not need to create weight tensors beyond this exercise, but hopefully by doing it this time, you will have a better understanding (and appreciation) of the details that are often lost in an API call to `model.fit()`, for exampe.

The table below shows Amelia's decisions on whether or not to go to a concert ($y$, the output or [labels](https://developers.google.com/machine-learning/glossary#label) in our example) based on three input variables, if she likes the band or not ($x_1$), if the weather is good or not ($x_2$), and if one of her friends will come ($x_3$). Together, $x_1$, $x_2$, and $x_3$ will be combined into our input tensor $X$.

Case # |Band good? ($x_1$) | Weather Good? ($x_2$) | Friend will come? ($x_3$) | Decision ($y$)
-------|----------------|--------------------|------------------------|-------------
1| Yes (1) | Yes(1) | Yes (1) | Yes (1)
2| No (0) | Yes(1) | Yes (1) | Yes (1)
3| Yes (1) | No (0) | Yes (1) | Yes (1)
4| No (0) | No (0) | Yes (1) | Yes (1)
5| Yes (1) | Yes (1) | No (0) | Yes (1)
6| No (0) | Yes (1) | No (0) | No (0)
7| Yes (1) | No (0) | No (0) | No (0)
8| No (0) | No (0) | No (0) | No (0)

Studying the table, you may see that Amelia places a lot of weight on whether her friends will go--even if she doesn't like the band and the weather will be bad, she'll go if friends are going! 

Since there are relatively few inputs and outputs, we could write these rules explicitly, but let's see if we can write a perceptron that can learn these rules from the data!

***

#### 1. Import libraries

Import the necessary libraries.

In [1]:
import tensorflow as tf
import pandas as pd
from tensorflow.keras import activations

from matplotlib import pyplot as plt

#### 2. Create an input data matrix

Create a 3 x 8 matrix for our input data. Remember that we have three inputs (we'll call them $x_1$, $x_2$, and $x_3$ for now), these are the columns in our input data.

The matrix below has the three input columns of our data table, using just the 0/1 values corresponding to the no/yes entries in the table. The comments help line up rows of the table with entries in our X variable.

```python
X = tf.Variable([[1.,1.,1.], # Case 1
                 [0.,1.,1.], # Case 2
                 [1.,0.,1.], # Case 3
                 [0.,0.,1.], # Case 4
                 [1.,1.,0.], # Case 5
                 [0.,1.,0.], # Case 6
                 [1.,0.,0.], # Case 7
                 [0.,0.,0.]], # Case 8
                 dtype = tf.float32)  # 3x8, input data table
print(X)
```

In [2]:
# Code it!
x = tf.Variable([[1.,1.,1.], # Case 1
                 [0.,1.,1.], # Case 2
                 [1.,0.,1.], # Case 3
                 [0.,0.,1.], # Case 4
                 [1.,1.,0.], # Case 5
                 [0.,1.,0.], # Case 6
                 [1.,0.,0.], # Case 7
                 [0.,0.,0.]], # Case 8
                dtype = tf.float32) #3x8, input data table

2023-07-12 14:24:44.970820: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE4.1 SSE4.2 AVX AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-07-12 14:24:45.736274: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1510] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 79125 MB memory:  -> device: 0, name: NVIDIA A100-SXM4-80GB, pci bus id: 0000:b7:00.0, compute capability: 8.0


#### 3. Create a label tensor
Create a tensor of labels to hold our 'ground truth'. This is the decision for each set of input whether or not to go to the concert. 

```python
# Outputs:       1, 2, 3, 4, 5, 6, 7, 8--one for each case in the table         
y = tf.Variable([1, 1, 1, 1, 1, 0, 0, 0], dtype = tf.float32) 

y = tf.reshape(y, [8,1])  
print(y)
```

In [11]:
# Code it!
# Outputs:       1, 2, 3, 4, 5, 6, 7, 8--one for each case in the table         
y = tf.Variable([1, 1, 1, 1, 1, 0, 0, 0], dtype = tf.float32) 

y = tf.reshape(y, [8,1])  
print(y)

tf.Tensor(
[[1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]], shape=(8, 1), dtype=float32)


#### 4. Define some constants to set shape of weight matrix
Define two constants to be used in the next step when we define the connections weight matrix.
We can use the number of columns in the X table to determine the number of features or how many $x_i$'s we need in our model. Since we are looking for a binary decision (go/don't go) we only need one output value.

```python
NUM_FEATURES = X.shape[1]
OUTPUT_SIZE = 1
```

In [12]:
# Code it!
NUM_FEATURES = x.shape[1]
OUTPUT_SIZE = 1

***

#### 5. Define connections weight matrix

![Diagram of the perceptron with 3 input variables (x1, x2, x3), 3 weights (w1, W2, w3) and the bias term. The perceptron body multiplies the inputs by the weights and sums them and the bias, resulting in the output--whether or not to go to the concert.](images/02.1_image_5.jpg)

We will need one weight for each feature, $x_i$ (is the band good, is the weather good, etc.), in our feature matrix, labelled $X$. These weights are our $w_i$'s. We don't know what value they should take, so we can initialize them to 0. Another common option is to use a random number to initialize the weights--this is one reason different runs of model training may give different answers.

```python
W = tf.Variable(tf.zeros([NUM_FEATURES, OUTPUT_SIZE]), dtype = tf.float32)
print(W)
```

In [13]:
# Code it!
W = tf.Variable(tf.zeros([NUM_FEATURES, OUTPUT_SIZE]), dtype = tf.float32)
print(W)

<tf.Variable 'Variable:0' shape=(3, 1) dtype=float32, numpy=
array([[0.],
       [0.],
       [0.]], dtype=float32)>


***

#### 6. Define bias variable

![](images/02.1_image_6.jpg)

Since we only have one neuron, we only need one bias value. Again, we'll initialize it to 0--a random number would be another option here. Again, each bias can be written as $b_i$ and the matrix of all biases as $B$.

```python
B = tf.Variable(tf.zeros([OUTPUT_SIZE, 1]), dtype = tf.float32)
print(B)
```

In [14]:
# Code it!
B = tf.Variable(tf.zeros([OUTPUT_SIZE, 1]), dtype = tf.float32)
print(B)

<tf.Variable 'Variable:0' shape=(1, 1) dtype=float32, numpy=array([[0.]], dtype=float32)>


***

#### 7. Define a perceptron function

![](images/02.1_image_7.jpg)

In this code block, we define a perceptron function, with one input argument, x, containing our three input data features. 

The function's first line implements a net input function.  It multiplies the input data matrix (x) by the weights (W) using the matrix multiplication function (matmul).  It then adds the bias (B) value to that product.

#### <img src='images/note_icon.svg' alt="Note icon" width=35 align=center> Note
>This is the essential function of a neuron: gather the inputs, multiply each input by the weight for that input, add the products up and add in the bias.

The function's second line implements an activation function. This determines how, if at all, the output of the neuron (calculated above) is changed before passing it on. Here we use the `tanh` activation function.  However, there are other TensorFlow options.  For example, you could use the `tf.sigmoid` function.  Or, select a function from the Keras activation (`activations`) library.  Do a search of the Keras documentation for a complete list of available functions.

Try out these other options, retrain the network, and see what happens.

```python
output = tf.sigmoid(z)
output = activations.relu(z)
output = activations.linear(z)
```

In [15]:
def perceptron(x):
    z = tf.add(tf.matmul(x, W), B)  # Net input function
    output = tf.tanh(z)             # Activation function
    return output

Execute the perceptron function to see its initial predictions before any training.  All of its predictions ought to be 0 (remember we set all the weights and the bias to 0--so whatever the inputs are, they are all multiplied by 0 and have 0 added to the sum). 

In [16]:
print(perceptron(x))        # Execute the perceptron to see its initial predictions before training.

tf.Tensor(
[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]], shape=(8, 1), dtype=float32)


#### 8. Training the Perceptron

Now that we have the elements of a simple, single node perceptron in place, let's train the network using backpropogation. The backpropagation is implemented in the optimizer algorythm, so we don't need to code that ourselves.

The [learning rate](https://developers.google.com/machine-learning/glossary#learning-rate) determines the size of the steps taken towards the global minimum while the optimizer manages the weight update process during backpropagation.  Here the Stochastic Gradient Descent (SGD) optimizer has been selected.

In [18]:
learning_rate = 0.01
optimizer = tf.optimizers.SGD(learning_rate)

#### 9. Train the perceptron for 1000 epochs

An [epoch](https://developers.google.com/machine-learning/glossary#epoch) is a full training pass over the entire dataset.  Our loss or error function is defined as a lambda function (a single-line,inline function) in the first line of code in the loop block.  We use the `sigmoid_cross_entropy_with_logits` function, an appropriate choice for this application to calculate how far our predicted results are from the known results. We will not get into the technical details here as that is outside the scope of this learning experience. The second line is where our SGD optimizer seeks to minimize the model's total error.

In [19]:
no_of_epochs = 1000

for n in range(no_of_epochs):
    loss = lambda:abs(tf.reduce_mean(tf.nn.sigmoid_cross_entropy_with_logits(labels = y, logits = perceptron(x))))
    optimizer.minimize(loss, [W, B])

2023-07-12 14:32:45.084322: I tensorflow/stream_executor/cuda/cuda_blas.cc:1760] TensorFloat-32 will be used for the matrix multiplication. This will only be logged once.


#### 10. Print the weights
<img alt="Friendship gif" src="https://i.giphy.com/media/3oEdvaba4h0I536VYQ/giphy.webp" align="right" width="300">

Notice that the model has learned that fiendship matters to Amelia! Of the weights, the 3rd one has the largest value.

Given that the input from each feature will be a 0 or a 1, multiplying by a larger weight will increase the contribution of that feature in the summation of all input-by-weight products ($x_i * w_i$) in determining the output of the neuron.

The perceptron has learned how to take the three input variables and weight them to predict the output. 

```python
print(W)
```

In [20]:
# Code it!
print(W)

<tf.Variable 'Variable:0' shape=(3, 1) dtype=float32, numpy=
array([[0.2906849],
       [0.2906849],
       [1.0723362]], dtype=float32)>


#### 11. Print the bias

```python
print(B)
```

In [21]:
# Code it!
print(B)

<tf.Variable 'Variable:0' shape=(1, 1) dtype=float32, numpy=array([[-0.33376604]], dtype=float32)>


In [22]:
# Code it!
print(perceptron(x))

tf.Tensor(
[[ 0.866769  ]
 [ 0.7736095 ]
 [ 0.7736095 ]
 [ 0.6282805 ]
 [ 0.24266483]
 [-0.0430545 ]
 [-0.0430545 ]
 [-0.32190067]], shape=(8, 1), dtype=float32)


Let's bring the x, y and predictions together to make it easier to read. Remember that `Yes=1` and `No=0` in the table.

In [23]:
x_df = pd.DataFrame(x.numpy(), columns=['Like Band?', 'Weather Good?', 'Friend Going?'])
y_df = pd.DataFrame(y.numpy(), columns=['Go to Concert?'])
pred_df = pd.DataFrame(perceptron(x).numpy(), columns=['Predictions'])
df = pd.concat([x_df, y_df, pred_df], axis=1)
df

Like Band?  Weather Good?  Friend Going?  Go to Concert?  Predictions
0         1.0            1.0            1.0             1.0     0.866769
1         0.0            1.0            1.0             1.0     0.773610
2         1.0            0.0            1.0             1.0     0.773610
3         0.0            0.0            1.0             1.0     0.628281
4         1.0            1.0            0.0             1.0     0.242665
5         0.0            1.0            0.0             0.0    -0.043054
6         1.0            0.0            0.0             0.0    -0.043054
7         0.0            0.0            0.0             0.0    -0.321901

#### 13. Let's see how different choices would change the results

Let's make some changes to Amelia's decisions and see what happens to the learned weights and predictions. 

##### Change 1: Amelia hates bad weather:

`y = tf.Variable([1, 1, 0, 0, 1, 0, 0, 0], dtype = tf.float32)`

##### Change 2: Amelia only goes to bands she likes

`y = tf.Variable([1, 0, 1, 0, 1, 0, 1, 0], dtype = tf.float32)`

Feel free to play with other parts of the model, everying but the X inputs is replicated below to put it all in one place for easy reference. Comments point out hyperparameters that you might want to change.

In [28]:
## From step 3
# Outputs:       1, 2, 3, 4, 5, 6, 7, 8--one for each case in the table         
y = tf.Variable([1, 0, 1, 0, 1, 0, 1, 0], dtype = tf.float32) # Change 1 has been made, you'll need to make change 2
y = tf.reshape(y, [8,1])  # convert to 4x1

## From step 4
NUM_FEATURES = x.shape[1]
OUTPUT_SIZE = 1

## From step 5
W = tf.Variable(tf.zeros([NUM_FEATURES, OUTPUT_SIZE]), dtype = tf.float32)

## From step 6
B = tf.Variable(tf.zeros([OUTPUT_SIZE, 1]), dtype = tf.float32)

## From step 7
def perceptron(x):
    z = tf.add(tf.matmul(x, W), B)      
    output = tf.tanh(z)                  # Activation function is a good hyperparameter to change 
    return output

## From step 8
learning_rate = 0.01  # Learning rate is a good hyperparameter to change
optimizer = tf.optimizers.SGD(learning_rate)

## From step 9
no_of_epochs = 1000 # Number of epochs is a good hyperparameter to change

for n in range(no_of_epochs):
    loss = lambda:abs(tf.reduce_mean(tf.nn.sigmoid_cross_entropy_with_logits(labels = y, logits = perceptron(x))))
    optimizer.minimize(loss, [W, B])
    
## From steps 10 on, printing the output
print(f'Weights: {W}')
print(f'Bias: {B}')

x_df = pd.DataFrame(x.numpy(), columns=['Like Band?', 'Weather Good?', 'Friend Going?'])
y_df = pd.DataFrame(y.numpy(), columns=['Go to Concert?'])
pred_df = pd.DataFrame(perceptron(x).numpy(), columns=['Predictions'])
df = pd.concat([x_df, y_df, pred_df], axis=1)
df

Weights: <tf.Variable 'Variable:0' shape=(3, 1) dtype=float32, numpy=
array([[ 1.4559332 ],
       [-0.15017778],
       [-0.15017778]], dtype=float32)>
Bias: <tf.Variable 'Variable:0' shape=(1, 1) dtype=float32, numpy=array([[-0.46442908]], dtype=float32)>


Like Band?  Weather Good?  Friend Going?  Go to Concert?  Predictions
0         1.0            1.0            1.0             1.0     0.598719
1         0.0            1.0            1.0             0.0    -0.643887
2         1.0            0.0            1.0             1.0     0.686511
3         0.0            0.0            1.0             0.0    -0.547362
4         1.0            1.0            0.0             1.0     0.686511
5         0.0            1.0            0.0             0.0    -0.547362
6         1.0            0.0            0.0             1.0     0.758003
7         0.0            0.0            0.0             0.0    -0.433687